defaults:
  - task: libero_90
  - algo: diffusion_policy
  - _self_


training:
  use_tqdm: true
  n_epochs: 0
  do_profile: false
  resume: false
  load_obs: false

rollout:
  enabled: true
  interval: 25
  rollouts_per_env: 50
  max_episode_length: ${task.horizon}
  num_parallel_envs: 1
  n_video: 0

exp_name: pretrain_ # 
variant_name: null
seed: 10000
device: cuda:0
stage: 2 # 0 - pretrain autoencoder, 1 - train multitask, 2 - finetune multitask
output_prefix: /home/yeyifan/workplace/embodied/experiments/
data_prefix: ./data
make_unique_experiment_dir: true

checkpoint_path: null

